version: 1
formatters:
  file_format:
    format: '%(asctime)s - %(lineno)s - %(levelname)s - %(name)s - %(message)s'
  console_format:
    format: '%(asctime)s - %(message)s'
    datefmt: '%d.%m %H:%M'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console_format
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: file_format
    filename: "log.log"

root:
  level: INFO
  handlers: [file, console]